### ISSUE TITLE
No package hue-4.3.0 available.

### ISSUE THREAD

**Issue by LeonanCarvalho** [snakecy/ambari-hue-service#1]
Hi, thanks for providing a new version of this ambari-hue-service,

But I guess something is missing.

I'm trying to install it on a HDP 3.1 and I'm receiving the folloging error:

```
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.1/services/HUE/package/scripts/hue_server.py", line 104, in <module>
    HueServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.1/services/HUE/package/scripts/hue_server.py", line 38, in install
    download_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.1/services/HUE/package/scripts/common.py", line 81, in download_hue
    Execute('yum install -y hue-4.3.0')
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'yum install -y hue-4.3.0' returned 1. Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: linorg.usp.br
 * centos-sclo-rh: mirror.globo.com
 * epel: mirror.globo.com
 * extras: mirror.globo.com
 * updates: mirror.globo.com
No package hue-4.3.0 available.
Error: Nothing to do
```

Is this script considering a local repository?

Thanks

**Comment by snakecy** [comment]
@LeonanCarvalho  The package hue-4.3.0 is self-packaging mirror. you should download it first.(https://github.com/cloudera/hue/releases)

**Comment by snakecy** [comment]
no issue, closed.
